language: c

addons:
  apt:
    packages:
      - build-essential
      - lib32asound2-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libgd2-xpm
      - libcairo2-dev   
      - libpango1.0-dev

matrix:
  include:
    - os: linux
      script:
        - cd build.linux64x64/squeak.cog.spur/build
        - ./mvm
    - os: osx
      script:
        - cd build.macos32x86/squeak.cog.spur/build
        - ./mvm -a