language: c

addons:
  apt:
    packages:
      # this are requirements for building the vm
      - debhelper
      - devscripts
      - libasound2-dev
      - libssl-dev
      - libfreetype6-dev
      - libx11-dev
      - libxext-dev
      - gcc-multilib
      - uuid-dev

matrix:
  include:
    - os: linux
      env: ARCH="linux64x64" FLAVOR="newspeak.cog.spur"
    - os: linux
      env: ARCH="linux64x64" FLAVOR="squeak.cog.spur"

    - os: linux
      env: ARCH="linux32x86" FLAVOR="newspeak.cog.spur"
      addons:
        apt:
          packages:
            - debhelper
            - devscripts
            - libc6-dev:i386
            - libasound2:i386
            - libasound2-dev:i386
            - libssl-dev:i386
            - libssl0.9.8:i386
            - libfreetype6-dev:i386
            - libx11-dev:i386
            - libsm-dev:i386
            - libice-dev:i386
            - libgl1-mesa-glx:i386
            - libgl1-mesa-dev:i386
            - libxext-dev:i386
            - libglapi-mesa:i386
            - gcc-multilib
            - uuid-dev:i386
    - os: linux
      env: ARCH="linux32x86" FLAVOR="squeak.cog.spur"
      addons:
        apt:
          packages:
            - debhelper
            - devscripts
            - libc6-dev:i386
            - libasound2:i386
            - libasound2-dev:i386
            - libssl-dev:i386
            - libssl0.9.8:i386
            - libfreetype6-dev:i386
            - libx11-dev:i386
            - libsm-dev:i386
            - libice-dev:i386
            - libgl1-mesa-glx:i386
            - libgl1-mesa-dev:i386
            - libxext-dev:i386
            - libglapi-mesa:i386
            - gcc-multilib
            - uuid-dev:i386
    - os: linux
      env: ARCH="linux32x86" FLAVOR="squeak.cog.v3"
      addons:
        apt:
          packages:
            - debhelper
            - devscripts
            - libc6-dev:i386
            - libasound2:i386
            - libasound2-dev:i386
            - libssl-dev:i386
            - libssl0.9.8:i386
            - libfreetype6-dev:i386
            - libx11-dev:i386
            - libsm-dev:i386
            - libice-dev:i386
            - libgl1-mesa-glx:i386
            - libgl1-mesa-dev:i386
            - libxext-dev:i386
            - libglapi-mesa:i386
            - gcc-multilib
            - uuid-dev:i386

    - os: osx
      env: ARCH="macos64x64" FLAVOR="newspeak.cog.spur"
    - os: osx
      env: ARCH="macos64x64" FLAVOR="pharo.cog.spur"
    - os: osx
      env: ARCH="macos64x64" FLAVOR="squeak.cog.spur"

    - os: osx
      env: ARCH="macos32x86" FLAVOR="newspeak.cog.spur"
    - os: osx
      env: ARCH="macos32x86" FLAVOR="pharo.cog.spur"
    - os: osx
      env: ARCH="macos32x86" FLAVOR="squeak.cog.spur"
    - os: osx
      env: ARCH="macos32x86" FLAVOR="squeak.cog.v3"

script:
  - ./.travis_build.sh

after_success:
  - curl -T "cog_${ARCH}_${FLAVOR}.tar.gz" -u "$DEPLOY_CREDENTIALS" https://www.hpi.uni-potsdam.de/hirschfeld/artefacts/cog/
