language: c

addons:
  apt:
    packages:
      - build-essential
      - lib32asound2-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - ia32-libs
      - gcc-multilib
      - g++multilib

script:
  - cd build.linux32x86/squeak.cog.spur/build
  - ./mvm