language: c

addons:
  apt:
    packages:
      - build-essential
      - lib32asound2-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libgd2-xpm
      - libcairo2-dev   
      - libpango1.0-dev

script:
  - cd build.linux64x64/squeak.cog.spur/build
  - ./mvm