language: c

addons:
  apt:
    packages:
      # this are to be able to execute a VM downloaded from the internet during build
      - lib32asound2
      - lib32z1
      - lib32ncurses5
      - lib32bz2-1.0
      - gvfs-daemons
      # this are requirements for building the vm
      - cmake
      - zip
      - bash-completion
      - git
      - xz-utils
      - debhelper
      - devscripts
      - libc6-dev
      - libasound2
      # - libasound2:i386
      - libasound2-dev
      # - libasound2-dev:i386
      - libssl-dev
      - libssl0.9.8
      - libfreetype6-dev
      - libx11-dev
      - libsm-dev
      - libice-dev
      - libgl1-mesa-glx
      - libgl1-mesa-dev
      - libxext-dev
      - libglapi-mesa
      - build-essential
      - gcc-multilib
      - g++
      - uuid-dev


matrix:
  include:
    - os: linux
      script:
        - cd build.linux64x64
        - ./squeak.cog.spur/build/mvm
        - tar czf coglinux64x64.tar.gz $TRAVIS_BUILD_DIR/products
        - curl -T coglinux64x64.tar.gz -u "$DEPLOY_CREDENTIALS" https://www.hpi.uni-potsdam.de/hirschfeld/artefacts/cog/ || true
    - os: osx
      script:
        - cd build.macos32x86
        - ./squeak.cog.spur/mvm
        - tar czf cogmacosx64x64.tar.gz Cocoa*.app
        - curl -T cogmacosx64x64.tar.gz -u "$DEPLOY_CREDENTIALS" https://www.hpi.uni-potsdam.de/hirschfeld/artefacts/cog/ || true
