language: c

addons:
  apt:
    packages:
      # this are requirements for building the vm
      - cmake
      - debhelper
      - devscripts
      - libasound2-dev
      - libssl-dev
      - libfreetype6-dev
      - libx11-dev
      - libxext-dev
      - build-essential
      - gcc-multilib
      - uuid-dev


matrix:
  include:
    # - os: linux
    #   env: COG_BUILD="linux64x64" COG_FLAVOR="newspeak.cog.spur"
    - os: linux
      env: COG_BUILD="linux64x64" COG_FLAVOR="squeak.cog.spur"

    # - os: linux
    #   env: COG_BUILD="linux32x86" COG_FLAVOR="newspeak.cog.spur"
    - os: linux
      env: COG_BUILD="linux32x86" COG_FLAVOR="squeak.cog.spur"
      addons:
        apt:
          packages:
            - cmake
            - debhelper
            - devscripts
            - libc6-dev:i386
            - libasound2:i386
            - libasound2-dev:i386
            - libssl-dev:i386
            - libssl0.9.8:i386
            - libfreetype6-dev:i386
            - libx11-dev:i386
            - libsm-dev:i386
            - libice-dev:i386
            - libgl1-mesa-glx:i386
            - libgl1-mesa-dev:i386
            - libxext-dev:i386
            - libglapi-mesa:i386
            - build-essential
            - gcc-multilib
            - uuid-dev:i386
    - os: linux
      env: COG_BUILD="linux32x86" COG_FLAVOR="squeak.cog.v3"
      addons:
        apt:
          packages:
            - cmake
            - debhelper
            - devscripts
            - libc6-dev:i386
            - libasound2:i386
            - libasound2-dev:i386
            - libssl-dev:i386
            - libssl0.9.8:i386
            - libfreetype6-dev:i386
            - libx11-dev:i386
            - libsm-dev:i386
            - libice-dev:i386
            - libgl1-mesa-glx:i386
            - libgl1-mesa-dev:i386
            - libxext-dev:i386
            - libglapi-mesa:i386
            - build-essential
            - gcc-multilib
            - uuid-dev:i386

    # - os: osx
    #   env: COG_BUILD="macos32x86" COG_FLAVOR="newspeak.cog.spur"
    - os: osx
      env: COG_BUILD="macos32x86" COG_FLAVOR="pharo.cog.spur"
    - os: osx
      env: COG_BUILD="macos32x86" COG_FLAVOR="squeak.cog.spur"
    - os: osx
      env: COG_BUILD="macos32x86" COG_FLAVOR="squeak.cog.v3"

    # - os: osx
    #   env: COG_BUILD="macos64x64" COG_FLAVOR="newspeak.cog.spur"
    - os: osx
      env: COG_BUILD="macos64x64" COG_FLAVOR="pharo.cog.spur"
    - os: osx
      env: COG_BUILD="macos64x64" COG_FLAVOR="squeak.cog.spur"

script:
  - ./.travis_build.sh

after_success:
  - curl -T "cog_${COG_BUILD}_${COG_FLAVOR}.tar.gz" -u "$DEPLOY_CREDENTIALS" https://www.hpi.uni-potsdam.de/hirschfeld/artefacts/cog/
