#!/bin/sh
rpm=`rpm --specfile squeak-vm.spec -q|head -n 1|sed 's/.*[^0-9]-//'`
ver=`echo $rpm|sed 's/[a-z].*//'`

if [ -r  /usr/src/redhat/RPMS/i386/squeak-vm-${rpm}.i386.rpm ] ; then
    echo squeak-vm-${rpm}.i386.rpm already exists
    echo 'forgot to update squeak-vm.spec?'
    echo press return to continue anyway
    read
fi

rm -f dist/Squeak-${ver}.src.tar.gz
(cd bld; make dist-src)

#(cd dist;wget http://squeakvm.org/unix/release/Squeak-${ver}.src.tar.gz)
if [ -r /usr/lib/libGL.so.1 ] ; then
    echo press return to temporarily disable GL lib and headers
    read
    sudo mkdir -p /usr/lib/GL-bak
    sudo mv /usr/lib/libGL* /usr/lib/GL-bak/
    sudo mv /usr/include/GL /usr/include/GL-bak
fi

sudo cp dist/Squeak-${ver}.src.tar.gz /usr/src/redhat/SOURCES
sudo rpmbuild -ba squeak-vm.spec

echo press return to reenable GL
read
sudo mv /usr/lib/GL-bak/* /usr/lib/
sudo rmdir /usr/lib/GL-bak 
sudo mv /usr/include/GL-bak /usr/include/GL

cd rpms
cp /usr/src/redhat/RPMS/i386/squeak-vm-${rpm}.i386.rpm .
cp /usr/src/redhat/SRPMS/squeak-vm-${rpm}.src.rpm .

echo press return to commit to svn
read
svn add squeak-vm-${rpm}.i386.rpm
svn add squeak-vm-${rpm}.src.rpm
svn commit

svn cp squeak-vm-${rpm}.i386.rpm ../yum
cd ../yum
createrepo -c cache . 
mv .olddata/.svn repodata/
rmdir .olddata
svn commit